### ISSUE TITLE
About face extractor’s scale

### ISSUE THREAD

**Issue by githuboflk** [sccsok/Locate-and-Verify#1]
I noticed that the scale is different in the code for face extraction, should I modify it to be the same?

**Comment by sccsok** [comment]
> I noticed that the scale is different in the code for face extraction, should I modify it to be the same?

The different scale parameters are able to ensure the facial proportions in the processed images of four subdatasets are as similar as possible.

**Comment by githuboflk** [comment]
> > I noticed that the scale is different in the code for face extraction, should I modify it to be the same?
> 
> The different scale parameters are able to ensure the facial proportions in the processed images of four subdatasets are as similar as possible.

Thanks. Can you provide the scale of test dataset or the code of extracting?

**Comment by githuboflk** [comment]
> > I noticed that the scale is different in the code for face extraction, should I modify it to be the same?
> 
> The different scale parameters are able to ensure the facial proportions in the processed images of four subdatasets are as similar as possible.


I noticed that the scale is different in the code for face extraction, should I modify it to be the same?

The different scale parameters are able to ensure the facial proportions in the processed images of four subdatasets are as similar as possible.

Thanks. Can you provide the scale of test dataset or the code of extracting?

**Comment by githuboflk** [comment]
> > I noticed that the scale is different in the code for face extraction, should I modify it to be the same?
> 
> The different scale parameters are able to ensure the facial proportions in the processed images of four subdatasets are as similar as possible.

Thanks. Can you provide the scale of test dataset or the code of extracting?
