### ISSUE TITLE
Has anyone reproduced the results in the paper?

### ISSUE THREAD

**Issue by githuboflk** [sccsok/Locate-and-Verify#12]

**Comment by githuboflk** [comment]
I asked the author about the test set last year. But there was no answer.

**Comment by sccsok** [comment]
The email on the paper is not in use, please contact me with 'sccsok1@gmail.com'.

**Comment by Tuesdayo** [comment]
> The email on the paper is not in use, please contact me with '[sccsok1@gmail.com](mailto:sccsok1@gmail.com)'.

@sccsok Hi. Hello, I'm also reproducing this paper. I have sent an email to this email. Looking forward to your reply.
