### ISSUE TITLE
FF++_original_youtube: No masks

### ISSUE THREAD

**Issue by mirro-yyf** [sccsok/Locate-and-Verify#3]
Hello ,thank you very much for selflessly sharing your deep forgery detection project. But currently, I have two questions that I need you to answer.
1.  I have preprocessed four types of forged videos in the FF++dataset, and the processed results are shown in the following figure. I am not sure if my understanding is correct. 
2. Additionally, I have seen "./ processes/create_ data_youtube.py"  there is a parameter in the file called masks, but FF++does not provide masks for youtube videos. How can I obtain these masks?
![github提问](https://github.com/sccsok/Locate-and-Verify/assets/89956031/0448c1e3-67ed-4c32-9830-f51f934a3f7c)

**Comment by sccsok** [comment]
@mirro-yyf To obtain similar images with other subdatasets, we use masks of Deepfakes to align youtube videos, but the masks are fixed as all zero pixels. And the masks you processed seems to be fine.

**Comment by mirro-yyf** [comment]
Thank you for your prompt response. However, in your homepage's readme, it was mentioned that a facial keypoint detection model needs to be downloaded, but I did not use it. The preprocessing steps for my data are as follows: 
1. Download the FF++dataset, including the video and corresponding mask; 
2. Extract frames from videos and masked videos; 
3. Run . /process/create_ xxx.py.

Is there any problem?
![github提问3](https://github.com/sccsok/Locate-and-Verify/assets/89956031/b9449511-3e22-4721-8a64-0a2037eaa13c)

**Comment by githuboflk** [comment]
> Thank you for your prompt response. However, in your homepage's readme, it was mentioned that a facial keypoint detection model needs to be downloaded, but I did not use it. The preprocessing steps for my data are as follows:
> 
> 1. Download the FF++dataset, including the video and corresponding mask;
> 2. Extract frames from videos and masked videos;
> 3. Run . /process/create_ xxx.py.
> 
> Is there any problem? ![github提问3](https://private-user-images.githubusercontent.com/89956031/283471495-b9449511-3e22-4721-8a64-0a2037eaa13c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNzM5OTgsIm5iZiI6MTcxODI3MzY5OCwicGF0aCI6Ii84OTk1NjAzMS8yODM0NzE0OTUtYjk0NDk1MTEtM2UyMi00NzIxLThhNjQtMGEyMDM3ZWFhMTNjLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDEwMTQ1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyZTYzNmI5MDQ4ZjJjMDVjMjk4NGVjZTA4MGUxMDgzZWU2YWJkNjIxMDRiZDIwZDM4Y2Q2MzI3MTNhYTNiNTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2Ycjuqte89IuBrvfY8XqJf9yeqWOv93c-y_FHpaT95c)

Did you reproduce the results in the paper?
