### ISSUE TITLE
issues about training

### ISSUE THREAD

**Issue by Gnonymous** [sccsok/Locate-and-Verify#5]
**Thanks for sharing!**
Following your steps in readme, l try to replicate your project.
But l meet some puzzling prombles: as the pictures blow shows, the acc is high to 100% in the beginning. Should l change other config?
Looking forward to your reply.
(l download Xception's weight, and l modify the 'xception' 's function, setting pretrain to 'True', as the paper said)
![image](https://github.com/sccsok/Locate-and-Verify/assets/105557628/389a2a7f-9a4c-4783-b01d-0fe6b391e0ae)
![image](https://github.com/sccsok/Locate-and-Verify/assets/105557628/13bfa843-09f6-484c-8149-f44d037e1502)

**Comment by Gnonymous** [comment]
I solved the problem of acc being 100% all the time by modifing some of the code, thanks again!
I would like to ask the second issuse：
do I need to modify the code of Xception to change pretrain to true while I am training, like this
![image](https://github.com/sccsok/Locate-and-Verify/assets/105557628/3d6bfd07-85f8-4fe7-bed5-310c1728ca92)

**Comment by sccsok** [comment]
> I solved the problem of acc being 100% all the time by modifing some of the code, thanks again! I would like to ask the second issuse： do I need to modify the code of Xception to change pretrain to true while I am training, like this ![image](https://private-user-images.githubusercontent.com/105557628/297263476-3d6bfd07-85f8-4fe7-bed5-310c1728ca92.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0Njg5NDIsIm5iZiI6MTcwNTQ2ODY0MiwicGF0aCI6Ii8xMDU1NTc2MjgvMjk3MjYzNDc2LTNkNmJmZDA3LTg1ZjgtNGZlNy1iZWQ1LTMxMGMxNzI4Y2E5Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExN1QwNTE3MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNmQ2OGNhMmU2ZTFkMjAwZjgxNTg3YzU4YThmN2FiNGRlZmY3MWI3YjEyMDQzN2UyODRjNjM3YzVlMjI1M2NmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TsN_YcXaHJ8emk33S47VZ3-yDd7e_A9zrHpvkbQE5Gw)

Yes, if you modify ``pretrained=true`` to use the pretrained weights of Xception, you should also modify the ``PRETAINED_WEIGHT_PATH`` to your path of ``xception-b5690688.pth``.

**Comment by Gnonymous** [comment]
Thanks for your answer.
So the reason why srouce code is `pretrained=False` is  to run  `test.py`?

**Comment by sccsok** [comment]
> Thanks for your answer. So the reason why srouce code is `pretrained=False` is to run `test.py`?

It will not affect the code of ``test.py``.

**Comment by guishengzhanga** [comment]
> I solved the problem of acc being 100% all the time by modifing some of the code, thanks again! I would like to ask the second issuse： do I need to modify the code of Xception to change pretrain to true while I am training, like this ![image](https://private-user-images.githubusercontent.com/105557628/297263476-3d6bfd07-85f8-4fe7-bed5-310c1728ca92.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2MjUxNzIsIm5iZiI6MTcwNTYyNDg3MiwicGF0aCI6Ii8xMDU1NTc2MjgvMjk3MjYzNDc2LTNkNmJmZDA3LTg1ZjgtNGZlNy1iZWQ1LTMxMGMxNzI4Y2E5Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOVQwMDQxMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZGYwODg1MDk4ZWY4NDUyMjQ1OWM2NTJlODI4ZjkzODJmY2I3MDRkODcxMmFjZTM3Nzk5ZGEwMzViMzljMmQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0KbWIqxQqCVl_FFFG171g2lOszk8mxyB65YdtqKXr-I)

Could you please tell me which part of the code you modified to solve this problem? Can you also tell me how to do it specifically?

**Comment by guishengzhanga** [comment]
> I solved the problem of acc being 100% all the time by modifing some of the code, thanks again! I would like to ask the second issuse： do I need to modify the code of Xception to change pretrain to true while I am training, like this ![image](https://private-user-images.githubusercontent.com/105557628/297263476-3d6bfd07-85f8-4fe7-bed5-310c1728ca92.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2MzAxODUsIm5iZiI6MTcwNTYyOTg4NSwicGF0aCI6Ii8xMDU1NTc2MjgvMjk3MjYzNDc2LTNkNmJmZDA3LTg1ZjgtNGZlNy1iZWQ1LTMxMGMxNzI4Y2E5Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOVQwMjA0NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OWEyMWVlODIwODg0ZTFjYTgwNDFiZDMxZjJhYTM0Y2Q0MDFkYjU0OGRmZThmZDY5MDJkM2EzNDYxM2U0NGQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gpgXlkWQyOk5dyJ2YSJhKwwP2n-u85sq_lgY7MqVOb8)

Could you please tell me which part of the code you modified to solve this problem? Can you also tell me how to do it specifically?

**Comment by Gnonymous** [comment]
> > I solved the problem of acc being 100% all the time by modifing some of the code, thanks again! I would like to ask the second issuse： do I need to modify the code of Xception to change pretrain to true while I am training, like this ![image](https://private-user-images.githubusercontent.com/105557628/297263476-3d6bfd07-85f8-4fe7-bed5-310c1728ca92.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2MzAxODUsIm5iZiI6MTcwNTYyOTg4NSwicGF0aCI6Ii8xMDU1NTc2MjgvMjk3MjYzNDc2LTNkNmJmZDA3LTg1ZjgtNGZlNy1iZWQ1LTMxMGMxNzI4Y2E5Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOVQwMjA0NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OWEyMWVlODIwODg0ZTFjYTgwNDFiZDMxZjJhYTM0Y2Q0MDFkYjU0OGRmZThmZDY5MDJkM2EzNDYxM2U0NGQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gpgXlkWQyOk5dyJ2YSJhKwwP2n-u85sq_lgY7MqVOb8)
> 
> 
> 
> Could you please tell me which part of the code you modified to solve this problem? Can you also tell me how to do it specifically?

Have you solve this problem?

**Comment by guishengzhanga** [comment]
> > > I solved the problem of acc being 100% all the time by modifing some of the code, thanks again! I would like to ask the second issuse： do I need to modify the code of Xception to change pretrain to true while I am training, like this ![image](https://private-user-images.githubusercontent.com/105557628/297263476-3d6bfd07-85f8-4fe7-bed5-310c1728ca92.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2MzAxODUsIm5iZiI6MTcwNTYyOTg4NSwicGF0aCI6Ii8xMDU1NTc2MjgvMjk3MjYzNDc2LTNkNmJmZDA3LTg1ZjgtNGZlNy1iZWQ1LTMxMGMxNzI4Y2E5Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOVQwMjA0NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OWEyMWVlODIwODg0ZTFjYTgwNDFiZDMxZjJhYTM0Y2Q0MDFkYjU0OGRmZThmZDY5MDJkM2EzNDYxM2U0NGQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gpgXlkWQyOk5dyJ2YSJhKwwP2n-u85sq_lgY7MqVOb8)
> > 
> > 
> > Could you please tell me which part of the code you modified to solve this problem? Can you also tell me how to do it specifically?
> 
> Have you solve this problem?

The problem has not been solved yet. Could you tell me how to solve it?

**Comment by guishengzhanga** [comment]
> > > I solved the problem of acc being 100% all the time by modifing some of the code, thanks again! I would like to ask the second issuse： do I need to modify the code of Xception to change pretrain to true while I am training, like this ![image](https://private-user-images.githubusercontent.com/105557628/297263476-3d6bfd07-85f8-4fe7-bed5-310c1728ca92.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2MzAxODUsIm5iZiI6MTcwNTYyOTg4NSwicGF0aCI6Ii8xMDU1NTc2MjgvMjk3MjYzNDc2LTNkNmJmZDA3LTg1ZjgtNGZlNy1iZWQ1LTMxMGMxNzI4Y2E5Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOVQwMjA0NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OWEyMWVlODIwODg0ZTFjYTgwNDFiZDMxZjJhYTM0Y2Q0MDFkYjU0OGRmZThmZDY5MDJkM2EzNDYxM2U0NGQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gpgXlkWQyOk5dyJ2YSJhKwwP2n-u85sq_lgY7MqVOb8)
> > 
> > 
> > Could you please tell me which part of the code you modified to solve this problem? Can you also tell me how to do it specifically?
> 
> Have you solve this problem?
Sorry. What I actually wanted to ask is how you address the issue of having the accuracy (acc) consistently at 100% during the initial stages of training.

**Comment by Gnonymous** [comment]
> > > > I solved the problem of acc being 100% all the time by modifing some of the code, thanks again! I would like to ask the second issuse： do I need to modify the code of Xception to change pretrain to true while I am training, like this ![image](https://private-user-images.githubusercontent.com/105557628/297263476-3d6bfd07-85f8-4fe7-bed5-310c1728ca92.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2MzAxODUsIm5iZiI6MTcwNTYyOTg4NSwicGF0aCI6Ii8xMDU1NTc2MjgvMjk3MjYzNDc2LTNkNmJmZDA3LTg1ZjgtNGZlNy1iZWQ1LTMxMGMxNzI4Y2E5Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOVQwMjA0NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OWEyMWVlODIwODg0ZTFjYTgwNDFiZDMxZjJhYTM0Y2Q0MDFkYjU0OGRmZThmZDY5MDJkM2EzNDYxM2U0NGQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gpgXlkWQyOk5dyJ2YSJhKwwP2n-u85sq_lgY7MqVOb8)
> 
> > > 
> 
> > > 
> 
> > > Could you please tell me which part of the code you modified to solve this problem? Can you also tell me how to do it specifically?
> 
> > 
> 
> > Have you solve this problem?
> 
> Sorry. What I actually wanted to ask is how you address the issue of having the accuracy (acc) consistently at 100% during the initial stages of training.
> 
> 

Have you meet the same problem? May be we can discuss it through other ways,like email or WeChat if you want.

**Comment by guishengzhanga** [comment]
> > > > > I solved the problem of acc being 100% all the time by modifing some of the code, thanks again! I would like to ask the second issuse： do I need to modify the code of Xception to change pretrain to true while I am training, like this ![image](https://private-user-images.githubusercontent.com/105557628/297263476-3d6bfd07-85f8-4fe7-bed5-310c1728ca92.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2MzAxODUsIm5iZiI6MTcwNTYyOTg4NSwicGF0aCI6Ii8xMDU1NTc2MjgvMjk3MjYzNDc2LTNkNmJmZDA3LTg1ZjgtNGZlNy1iZWQ1LTMxMGMxNzI4Y2E5Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOVQwMjA0NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OWEyMWVlODIwODg0ZTFjYTgwNDFiZDMxZjJhYTM0Y2Q0MDFkYjU0OGRmZThmZDY5MDJkM2EzNDYxM2U0NGQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gpgXlkWQyOk5dyJ2YSJhKwwP2n-u85sq_lgY7MqVOb8)
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > Could you please tell me which part of the code you modified to solve this problem? Can you also tell me how to do it specifically?
> > 
> > 
> > > 
> > 
> > 
> > > Have you solve this problem?
> > 
> > 
> > Sorry. What I actually wanted to ask is how you address the issue of having the accuracy (acc) consistently at 100% during the initial stages of training.
> 
> Have you meet the same problem? May be we can discuss it through other ways,like email or WeChat if you want.

WeChat：zgs178533

**Comment by Gnonymous** [comment]
> > > > > > I solved the problem of acc being 100% all the time by modifing some of the code, thanks again! I would like to ask the second issuse： do I need to modify the code of Xception to change pretrain to true while I am training, like this ![image](https://private-user-images.githubusercontent.com/105557628/297263476-3d6bfd07-85f8-4fe7-bed5-310c1728ca92.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2MzAxODUsIm5iZiI6MTcwNTYyOTg4NSwicGF0aCI6Ii8xMDU1NTc2MjgvMjk3MjYzNDc2LTNkNmJmZDA3LTg1ZjgtNGZlNy1iZWQ1LTMxMGMxNzI4Y2E5Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOVQwMjA0NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OWEyMWVlODIwODg0ZTFjYTgwNDFiZDMxZjJhYTM0Y2Q0MDFkYjU0OGRmZThmZDY5MDJkM2EzNDYxM2U0NGQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gpgXlkWQyOk5dyJ2YSJhKwwP2n-u85sq_lgY7MqVOb8)
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > > Could you please tell me which part of the code you modified to solve this problem? Can you also tell me how to do it specifically?
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > Have you solve this problem?
> > > 
> > > 
> > > Sorry. What I actually wanted to ask is how you address the issue of having the accuracy (acc) consistently at 100% during the initial stages of training.
> > 
> > 
> > Have you meet the same problem? May be we can discuss it through other ways,like email or WeChat if you want.
> 
> WeChat：zgs178533
l have added your Wechat,you can delete this message to protect your privacy.

**Comment by silencecmsj** [comment]
Can you offer me the file /splits/train.json val.json and test.json?

**Comment by silencecmsj** [comment]
> > I solved the problem of acc being 100% all the time by modifing some of the code, thanks again! I would like to ask the second issuse： do I need to modify the code of Xception to change pretrain to true while I am training, like this ![image](https://private-user-images.githubusercontent.com/105557628/297263476-3d6bfd07-85f8-4fe7-bed5-310c1728ca92.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2MzAxODUsIm5iZiI6MTcwNTYyOTg4NSwicGF0aCI6Ii8xMDU1NTc2MjgvMjk3MjYzNDc2LTNkNmJmZDA3LTg1ZjgtNGZlNy1iZWQ1LTMxMGMxNzI4Y2E5Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOVQwMjA0NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OWEyMWVlODIwODg0ZTFjYTgwNDFiZDMxZjJhYTM0Y2Q0MDFkYjU0OGRmZThmZDY5MDJkM2EzNDYxM2U0NGQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gpgXlkWQyOk5dyJ2YSJhKwwP2n-u85sq_lgY7MqVOb8)
> 
> Could you please tell me which part of the code you modified to solve this problem? Can you also tell me how to do it specifically?
Can you offer me the file /splits/train.json val.json and test.json?

**Comment by silencecmsj** [comment]
> > > > > > > I solved the problem of acc being 100% all the time by modifing some of the code, thanks again! I would like to ask the second issuse： do I need to modify the code of Xception to change pretrain to true while I am training, like this ![image](https://private-user-images.githubusercontent.com/105557628/297263476-3d6bfd07-85f8-4fe7-bed5-310c1728ca92.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2MzAxODUsIm5iZiI6MTcwNTYyOTg4NSwicGF0aCI6Ii8xMDU1NTc2MjgvMjk3MjYzNDc2LTNkNmJmZDA3LTg1ZjgtNGZlNy1iZWQ1LTMxMGMxNzI4Y2E5Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOVQwMjA0NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OWEyMWVlODIwODg0ZTFjYTgwNDFiZDMxZjJhYTM0Y2Q0MDFkYjU0OGRmZThmZDY5MDJkM2EzNDYxM2U0NGQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gpgXlkWQyOk5dyJ2YSJhKwwP2n-u85sq_lgY7MqVOb8)
> > > > 
> > > > 
> > > > > >
> > > > 
> > > > 
> > > > > >
> > > > 
> > > > 
> > > > > > Could you please tell me which part of the code you modified to solve this problem? Can you also tell me how to do it specifically?
> > > > 
> > > > 
> > > > > 
> > > > 
> > > > 
> > > > > Have you solve this problem?
> > > > 
> > > > 
> > > > Sorry. What I actually wanted to ask is how you address the issue of having the accuracy (acc) consistently at 100% during the initial stages of training.
> > > 
> > > 
> > > Have you meet the same problem? May be we can discuss it through other ways,like email or WeChat if you want.
> > 
> > 
> > WeChat：zgs178533
> > l have added your Wechat,you can delete this message to protect your privacy.
Can you offer me the file /splits/train.json val.json and test.json?
